DROP TABLE content;

CREATE TABLE content (
    id INT PRIMARY KEY CHECK (id BETWEEN CAST(X'A000' AS INT) AND CAST(X'AFFF' AS INT)), -- 40961 to 45055
    name text NOT NULL UNIQUE,
    content bytea NULL
);

INSERT INTO content (id, name) VALUES
(40961, 'MOST_RECENT_FIRMWARE_VERSION'),
(40962, 'WEATHER_FORECAST'),
(40963, 'SCHEDULE_FRIDAY'),
(40964, 'SCHEDULE_SATURDAY'),
(40965, 'SCHEDULE_SUNDAY');
